
[nano]
192.168.1.66

[agx]
192.168.1.76

[rk1]
192.168.1.72
192.168.1.228
192.168.1.83

[controlplane]
192.168.1.230

[rockpi]
192.168.1.77

[q6a]
192.168.1.80

[multi:children]
nano
agx
rk1
rockpi
q6a
controlplane

[nano:vars]
ansible_user=ubuntu
ansible_password=kepler109!

[agx:vars]
ansible_user=ubuntu
ansible_password=kepler109!

[rk1:vars]
ansible_user=ubuntu
ansible_password=kepler109!

[rockpi:vars]
ansible_user=radxa
ansible_password=radxa

[q6a:vars]
ansible_user=radxa
ansible_password=radxa

[controlplane:vars]
ansible_user=ubuntu
ansible_password=kepler109!

