---
- name: Copy certificate from local to remote hosts
  hosts: all
  become: yes
  tasks:
    - name: Copy certificate file to remote host
      ansible.builtin.shell: /usr/sbin/update-ca-certificates --fresh
      when: ansible_os_family == "Debian"
      args:
        # Prevents running the command if the file content hasn't changed
        creates: /etc/ssl/certs/ca-certificates.crt 
