---
- hosts: all
  become: yes  # Required for administrative privileges
  tasks:
    - name: Update apt cache and install required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - cryptsetup        
