---
- name: Install Docker
  hosts: rockpi
  become: yes
  tasks:
  - name: Update apt cache and install required packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - gnupg
  - name: Create keyring directory
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      owner: radxa # Replace with the desired owner
      group: radxa # Replace with the desired group
      mode: '0755'
  - name: Ensure a specific file is deleted
    ansible.builtin.file:
      path: /etc/apt/keyrings/docker.gpg
      state: absent
  - name: Download Docker keyring
    ansible.builtin.shell:
      cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  - name: Change keyring permissions
    ansible.builtin.shell:
      cmd: "chmod a+r /etc/apt/keyrings/docker.gpg"
  - name: Add docker repository to apt
    ansible.builtin.apt_repository:
      repo: deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
      state: present
  - name: Install Docker packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin
